language: bash

stages:
- lint
- test

env:
- VERBOSE=true

jobs:
  include:
  - stage: lint
    addons:
      apt:
        packages:
        - shellcheck
    script: shellcheck **/*.sh
  - stage: test
    script: ./test.sh
