language: bash

stages:
- lint
- test

env:
- VERBOSE=true

addons:
  apt:
    packages:
    - shellcheck

jobs:
  include:
  - stage: lint
    script: shellcheck **/*.sh
  - stage: test
    script: ./test.sh
